/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-07-19 13:03:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.CIMS.tab;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.gxlq.entity.EmailInfo;
import com.gxlq.service.imp.EmailInfoService;
import com.gxlq.service.IEmailInfoService;

public final class tab_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxlq.service.imp.EmailInfoService");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.gxlq.entity.EmailInfo");
    _jspx_imports_classes.add("com.gxlq.service.IEmailInfoService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	int pageSize=4;			//每一页 上显示信息的最大条数
	int firstPage=1;		//首页的页码
	int previousPage=1;		//上一页的页码
	int nextPage=1;			//下一页的页码
	int lastPage=1;			//最后一页的页码
	int currentPage=1;		//当前的页码
	
	//获取请求参数P，该值为要显示的页码
	String cp = request.getParameter("P");
	if(cp!=null){
		currentPage = Integer.parseInt(cp);
	}
	//调用业务方法，检索所有邮件信息
	   IEmailInfoService emailInfoService = new EmailInfoService();
	   
	   List<EmailInfo> emailInfos = emailInfoService.find();
	   int total = emailInfos.size(); //最记录条数
	   //分页
	   emailInfos = emailInfoService.find(currentPage,pageSize);
	   
	   //最后一页的页码
	   if(total%pageSize==0){
		   lastPage = total/pageSize;
	   }else{
		   lastPage = total/pageSize + 1;
	   }
	   
		//得到上一页的页号
	   previousPage=currentPage-1;
	   if(previousPage<=firstPage){
		previousPage=firstPage;
	   }
		
	   //得到下一页的页号
	   nextPage=currentPage+1;
	   if(nextPage>=lastPage){
		 nextPage=lastPage;
	   }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>添加邮件</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write(".STYLE1 {font-size: 12px}\r\n");
      out.write(".STYLE3 {font-size: 12px; font-weight: bold; }\r\n");
      out.write(".STYLE4 {\r\n");
      out.write("\tcolor: #03515d;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var  highlightcolor='#c1ebff';\r\n");
      out.write("//此处clickcolor只能用win系统颜色代码才能成功,如果用#xxxxxx的代码就不行,还没搞清楚为什么:(\r\n");
      out.write("var  clickcolor='#51b2f6';\r\n");
      out.write("function  changeto(){\r\n");
      out.write("source=event.srcElement;\r\n");
      out.write("if  (source.tagName==\"TR\"||source.tagName==\"TABLE\")\r\n");
      out.write("return;\r\n");
      out.write("while(source.tagName!=\"TD\")\r\n");
      out.write("source=source.parentElement;\r\n");
      out.write("source=source.parentElement;\r\n");
      out.write("cs  =  source.children;\r\n");
      out.write("//alert(cs.length);\r\n");
      out.write("if  (cs[1].style.backgroundColor!=highlightcolor&&source.id!=\"nc\"&&cs[1].style.backgroundColor!=clickcolor)\r\n");
      out.write("for(i=0;i<cs.length;i++){\r\n");
      out.write("\tcs[i].style.backgroundColor=highlightcolor;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function  changeback(){\r\n");
      out.write("if  (event.fromElement.contains(event.toElement)||source.contains(event.toElement)||source.id==\"nc\")\r\n");
      out.write("return\r\n");
      out.write("if  (event.toElement!=source&&cs[1].style.backgroundColor!=clickcolor)\r\n");
      out.write("//source.style.backgroundColor=originalcolor\r\n");
      out.write("for(i=0;i<cs.length;i++){\r\n");
      out.write("\tcs[i].style.backgroundColor=\"\";\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function  clickto(){\r\n");
      out.write("source=event.srcElement;\r\n");
      out.write("if  (source.tagName==\"TR\"||source.tagName==\"TABLE\")\r\n");
      out.write("return;\r\n");
      out.write("while(source.tagName!=\"TD\")\r\n");
      out.write("source=source.parentElement;\r\n");
      out.write("source=source.parentElement;\r\n");
      out.write("cs  =  source.children;\r\n");
      out.write("//alert(cs.length);\r\n");
      out.write("if  (cs[1].style.backgroundColor!=clickcolor&&source.id!=\"nc\")\r\n");
      out.write("for(i=0;i<cs.length;i++){\r\n");
      out.write("\tcs[i].style.backgroundColor=clickcolor;\r\n");
      out.write("}\r\n");
      out.write("else\r\n");
      out.write("for(i=0;i<cs.length;i++){\r\n");
      out.write("\tcs[i].style.backgroundColor=\"\";\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   function xxx(n){\r\n");
      out.write("\t   //重新跳转到tab.jsp，即“刷新tab.jsp”,且把要显示的号码以请求参数的方法进行传递，如 P=4\r\n");
      out.write("\t   window.location.href=\"http://192.168.1.167:8080/cims_gjmy/CIMS/tab/tab.jsp?P=\"+n;\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"30\" background=\"images/tab_05.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"12\" height=\"30\"><img src=\"images/tab_03.gif\" width=\"12\" height=\"30\" /></td>\r\n");
      out.write("        <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"46%\" valign=\"middle\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"5%\"><div align=\"center\"><img src=\"images/tb.gif\" width=\"16\" height=\"16\" /></div></td>\r\n");
      out.write("                <td width=\"95%\" class=\"STYLE1\"><span class=\"STYLE3\">你当前的位置</span>：[业务中心]-[我的邮件]</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"54%\"><table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"60\"><table width=\"87%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">\r\n");
      out.write("                      <input type=\"checkbox\" name=\"checkbox62\" value=\"checkbox\" />\r\n");
      out.write("                    </div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">全选</div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("                <td width=\"60\"><table width=\"90%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"><img src=\"images/22.gif\" width=\"14\" height=\"14\" /></div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"><a href=\"http://192.168.1.167:8080/cims_gjmy/CIMS/tab/add.jsp\">新增</a></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("                <td width=\"60\"><table width=\"90%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"><img src=\"images/33.gif\" width=\"14\" height=\"14\" /></div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">修改</div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("                <td width=\"52\"><table width=\"88%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"><img src=\"images/11.gif\" width=\"14\" height=\"14\" /></div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">删除</div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"16\"><img src=\"images/tab_07.gif\" width=\"16\" height=\"30\" /></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"8\" background=\"images/tab_12.gif\">&nbsp;</td>\r\n");
      out.write("        <td><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"b5d6e6\" onmouseover=\"changeto()\"  onmouseout=\"changeback()\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"3%\" height=\"22\" background=\"images/bg.gif\" bgcolor=\"#FFFFFF\"><div align=\"center\">\r\n");
      out.write("              <input type=\"checkbox\" name=\"checkbox\" value=\"checkbox\" />\r\n");
      out.write("            </div></td>\r\n");
      out.write("            <td width=\"3%\" height=\"22\" background=\"images/bg.gif\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\">序号</span></div></td>\r\n");
      out.write("            <td width=\"12%\" height=\"22\" background=\"images/bg.gif\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\">接收号码</span></div></td>\r\n");
      out.write("            <td width=\"14%\" height=\"22\" background=\"images/bg.gif\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\">发送时间</span></div></td>\r\n");
      out.write("            <td width=\"18%\" background=\"images/bg.gif\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\">邮件地址</span></div></td>\r\n");
      out.write("            <td width=\"23%\" height=\"22\" background=\"images/bg.gif\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\">内容</span></div></td>\r\n");
      out.write("            <td width=\"15%\" height=\"22\" background=\"images/bg.gif\" bgcolor=\"#FFFFFF\" class=\"STYLE1\"><div align=\"center\">基本操作</div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          ");

          for(EmailInfo emailinfo:emailInfos){
          
      out.write("\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\">\r\n");
      out.write("              <input type=\"checkbox\" name=\"checkbox2\" value=\"checkbox\" />\r\n");
      out.write("            </div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("              <div align=\"center\">");
      out.print(emailInfos.indexOf(emailinfo)+1);
      out.write("</div>\r\n");
      out.write("            </div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\">");
      out.print(emailinfo.getReceivenumber() );
      out.write("</span></div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\">");
      out.print(emailinfo.getSendtime() );
      out.write(" </span></div></td>\r\n");
      out.write("            <td bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\">");
      out.print(emailinfo.getEmailaddress() );
      out.write("</span></div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\">");
      out.print(emailinfo.getContent() );
      out.write("</span></div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE4\"><img src=\"images/edt.gif\" width=\"16\" height=\"16\" /><a href=\"http://192.168.1.167:8080/cims_gjmy/emailinfo?OP=toupdate&id=");
      out.print(emailinfo.getId());
      out.write("\">编辑</a>&nbsp; &nbsp;<img src=\"images/del.gif\" width=\"16\" height=\"16\" /><a href=\"http://192.168.1.167:8080/cims_gjmy/emailinfo?id=");
      out.print(emailinfo.getId());
      out.write("\">删除</a></span></div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"8\" background=\"images/tab_15.gif\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"35\" background=\"images/tab_19.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"12\" height=\"35\"><img src=\"images/tab_18.gif\" width=\"12\" height=\"35\" /></td>\r\n");
      out.write("        <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class=\"STYLE4\">&nbsp;&nbsp;共有 ");
      out.print(total );
      out.write(" 条记录，当前第 ");
      out.print(currentPage );
      out.write('/');
      out.print(lastPage );
      out.write("  页</td>\r\n");
      out.write("            <td><table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=\"40\"><img src=\"images/first.gif\" width=\"37\" height=\"15\" onclick=\"xxx(");
      out.print(firstPage);
      out.write(")\"/></td>\r\n");
      out.write("                  <td width=\"45\"><img src=\"images/back.gif\" width=\"43\" height=\"15\" onclick=\"xxx(");
      out.print(previousPage);
      out.write(")\"/></td>\r\n");
      out.write("                  <td width=\"45\"><img src=\"images/next.gif\" width=\"43\" height=\"15\" onclick=\"xxx(");
      out.print(nextPage);
      out.write(")\"/></td>\r\n");
      out.write("                  <td width=\"40\"><img src=\"images/last.gif\" width=\"37\" height=\"15\" onclick=\"xxx(");
      out.print(lastPage);
      out.write(")\"/></td>\r\n");
      out.write("                  <td width=\"100\"><div align=\"center\"><span class=\"STYLE1\">转到第\r\n");
      out.write("                    <input name=\"textfield\" type=\"text\" size=\"4\" onclick=\"xxx(document.getElementById('page').value)\" style=\"height:12px; width:20px; border:1px solid #999999;\" /> \r\n");
      out.write("                    页 </span></div></td>\r\n");
      out.write("                  <td width=\"40\"><img src=\"images/go.gif\" width=\"37\" height=\"15\" /></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"16\"><img src=\"images/tab_20.gif\" width=\"16\" height=\"35\" /></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
