/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-07-22 08:13:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.CIMS.tab;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.gxlq.service.IOperatorService;
import com.gxlq.service.imp.OperatorService;
import com.gxlq.entity.Operator;

public final class updateoperator_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.gxlq.service.imp.OperatorService");
    _jspx_imports_classes.add("com.gxlq.entity.Operator");
    _jspx_imports_classes.add("com.gxlq.service.IOperatorService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");

 String path = request.getContextPath();
 String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
 
      out.write('\r');
      out.write('\n');
      out.write(' ');

  Object obj = session.getAttribute("OPERATOR");
  Operator operator = new Operator();
  if(obj!=null){
	  operator = (Operator) obj;
  }
 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write(".STYLE1 {font-size: 12px}\r\n");
      out.write(".STYLE3 {font-size: 12px; font-weight: bold; }\r\n");
      out.write(".STYLE4 {\r\n");
      out.write("\tcolor: #03515d;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function tj(){\r\n");
      out.write("\t//根据id获取html页面中的表单，并提交\r\n");
      out.write("\twindow.document.getElementById(\"frm\").submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form id=\"frm\" action=\"http://192.168.1.167:8080/cims_gjmy/operator?OP=update&id=");
      out.print(operator.getId());
      out.write("&roleid=");
      out.print(operator.getRole().getId());
      out.write("\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"30\" background=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/tab_05.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"12\" height=\"30\"><img src=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/tab_03.gif\" width=\"12\" height=\"30\" /></td>\r\n");
      out.write("        <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"46%\" valign=\"middle\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"5%\"><div align=\"center\"><img src=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/tb.gif\" width=\"16\" height=\"16\" /></div></td>\r\n");
      out.write("                <td width=\"95%\" class=\"STYLE1\"><span class=\"STYLE3\">你当前的位置</span>：[权限管理]-[修改用户资料]</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"54%\"><table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"60\"><table width=\"87%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\">\r\n");
      out.write("                     \r\n");
      out.write("                    </div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("                <td width=\"60\"><table width=\"90%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"></div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("                <td width=\"60\"><table width=\"90%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"></div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("                <td width=\"52\"><table width=\"88%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"></div></td>\r\n");
      out.write("                    <td class=\"STYLE1\"><div align=\"center\"></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"16\"><img src=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/tab_07.gif\" width=\"16\" height=\"30\" /></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"8\" background=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/tab_12.gif\">&nbsp;</td>\r\n");
      out.write("        <td><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"b5d6e6\" onmouseover=\"changeto()\"  onmouseout=\"changeback()\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"3%\" height=\"22\" background=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/bg.gif\" bgcolor=\"#FFFFFF\"><div align=\"center\">\r\n");
      out.write("            \r\n");
      out.write("            </div></td>\r\n");
      out.write("            <td width=\"3%\" height=\"22\" background=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/bg.gif\" bgcolor=\"#FFFFFF\"><div align=\"center\"><span class=\"STYLE1\"></span></div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("           <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("              <div align=\"center\">密码：</div>\r\n");
      out.write("            </div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("              <div align=\"center\"><input type=\"text\" name=\"textfield1\" value=\"");
      out.print(operator.getPassword() );
      out.write("\"/></div> \r\n");
      out.write("            </div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("       \r\n");
      out.write("          <tr>\r\n");
      out.write("           <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("              <div align=\"center\">联系方式：</div>\r\n");
      out.write("            </div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("              <div align=\"center\"><!-- 使用下拉框<input type=\"text\" name=\"textfield2\" value=\"");
      out.print(operator.getTel() );
      out.write("\"/> --> \r\n");
      out.write("  \r\n");
      out.write("\t           <input type=\"text\" name=\"textfield2\" value=\"");
      out.print(operator.getTel() );
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("           </div> \r\n");
      out.write("            </div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          \r\n");
      out.write("          <tr>\r\n");
      out.write("           <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("             <div align=\"center\">头像：</div>\r\n");
      out.write("            </div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("             <div align=\"center\"><img id=\"\"  src=\"http://192.168.1.167:8080/cims_gjmy/");
      out.print(operator.getPic() );
      out.write("\" style=\"width:40px\">\r\n");
      out.write("              \t 请选择头像：<input type=\"file\" name=\"pic\"/>\t\r\n");
      out.write("\t</div> \r\n");
      out.write("            </div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          \r\n");
      out.write("          <tr>\r\n");
      out.write("           <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("              <div align=\"center\">预留：</div>\r\n");
      out.write("            </div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("              <div align=\"center\"><input type=\"text\" name=\"textfield4\" value=\"");
      out.print(operator.getReserve() );
      out.write("\"/></div> \r\n");
      out.write("            </div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          \r\n");
      out.write("           <tr>\r\n");
      out.write("             <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("              <div align=\"center\"></div>\r\n");
      out.write("            </div></td>\r\n");
      out.write("            <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("            <input type=\"hidden\" id=\"id\" value=\"");
      out.print(operator.getId() );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"username\" value=\"");
      out.print(operator.getUsername());
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"roleid\" value=\"");
      out.print(operator.getRole().getId());
      out.write("\">\r\n");
      out.write("              <div align=\"center\"><input type=\"button\" value=\"确定\" onclick=\"tj()\"/></div>\r\n");
      out.write("            </div></td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           \r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"8\" background=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/tab_15.gif\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"35\" background=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/tab_19.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"12\" height=\"35\"><img src=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/tab_18.gif\" width=\"12\" height=\"35\" /></td>\r\n");
      out.write("        <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class=\"STYLE4\"></td>\r\n");
      out.write("            <td><table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=\"40\"></td>\r\n");
      out.write("                  <td width=\"45\"></td>\r\n");
      out.write("                  <td width=\"45\"></td>\r\n");
      out.write("                  <td width=\"40\"></td>\r\n");
      out.write("                  <td width=\"100\"><div align=\"center\"></div></td>\r\n");
      out.write("                  <td width=\"40\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"16\"><img src=\"");
      out.print(basePath );
      out.write("CIMS/tab/images/tab_20.gif\" width=\"16\" height=\"35\" /></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</head>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
