/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-07-22 10:00:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.CIMS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gxlq.entity.Authorization;
import com.gxlq.entity.Operator;
import com.gxlq.service.imp.AuthorizationService;
import com.gxlq.service.IAuthorizationService;
import com.gxlq.service.IRoleService;
import com.gxlq.entity.Menu;
import java.util.List;
import com.gxlq.service.imp.MenuService;
import com.gxlq.service.IMenuService;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxlq.entity.Authorization");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.gxlq.entity.Operator");
    _jspx_imports_classes.add("com.gxlq.service.imp.AuthorizationService");
    _jspx_imports_classes.add("com.gxlq.service.IRoleService");
    _jspx_imports_classes.add("com.gxlq.service.IMenuService");
    _jspx_imports_classes.add("com.gxlq.entity.Menu");
    _jspx_imports_classes.add("com.gxlq.service.IAuthorizationService");
    _jspx_imports_classes.add("com.gxlq.service.imp.MenuService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write(".STYLE1 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write(".STYLE3 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #033d61;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".menu_title SPAN {\r\n");
      out.write("\tFONT-WEIGHT: bold; LEFT: 3px; COLOR: #ffffff; POSITION: relative; TOP: 2px \r\n");
      out.write("}\r\n");
      out.write(".menu_title2 SPAN {\r\n");
      out.write("\tFONT-WEIGHT: bold; LEFT: 3px; COLOR: #FFCC00; POSITION: relative; TOP: 2px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("var he=document.body.clientHeight-105\r\n");
      out.write("document.write(\"<div id=tt style=height:\"+he+\";overflow:hidden>\")\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"165\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"28\" background=\"images/main_40.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"19%\">&nbsp;</td>\r\n");
      out.write("        <td width=\"81%\" height=\"20\"><span class=\"STYLE1\">管理菜单</span></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"top\"><table width=\"151\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        \r\n");
      out.write("        ");

           Object obj = session.getAttribute("OPERATOR");
           Operator operator = new Operator();
        	if(obj!=null){
        		operator = (Operator)obj;
        	}
        	
        	int roleid = operator.getRole().getId();
        	IAuthorizationService ias = new AuthorizationService();
        	List<Authorization> authorizations = ias.findByRole(roleid);
        	
        
      out.write("\r\n");
      out.write("        ");

		    IMenuService ims = new MenuService();
		    //查找父菜单
		    List<Menu> menus = ims.findByParent(0);
		    for(Menu menu:menus){
		    	 for(Authorization au:authorizations){ 
		    		if(menu.getId()==au.getMenu().getId()){
    	
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"23\" background=\"images/main_47.gif\" id=\"imgmenu");
      out.print(menu.getId() );
      out.write("\" class=\"menu_title\" onMouseOver=\"this.className='menu_title2';\" onClick=\"showsubmenu(");
      out.print(menu.getId() );
      out.write(")\" onMouseOut=\"this.className='menu_title';\" style=\"cursor:hand\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"18%\">&nbsp;</td>\r\n");
      out.write("                <td width=\"82%\" class=\"STYLE1\">");
      out.print(menu.getName() );
      out.write("</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td background=\"images/main_51.gif\" id=\"submenu");
      out.print(menu.getId());
      out.write("\">\r\n");
      out.write("            ");
break;
           	      	}
		    }
		    
      out.write("\r\n");
      out.write("\t\t\t <div class=\"sec_menu\" >  \r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td><table width=\"90%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                 ");
 
				    List<Menu> sons = ims.findByParent(menu.getId());
				    for(Menu son:sons){
				    	for(Authorization au:authorizations){
				    		if(son.getId()==au.getMenu().getId()){
				 
      out.write("\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td width=\"16%\" height=\"25\"><div align=\"center\"><img src=\"images/left.gif\" width=\"10\" height=\"10\" /></div></td>\r\n");
      out.write("                    <td width=\"84%\" height=\"23\"><table width=\"95%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td height=\"20\" style=\"cursor:hand\" onmouseover=\"this.style.borderStyle='solid';this.style.borderWidth='1';borderColor='#7bc4d3';\r\n");
      out.write("                          \"onmouseout=\"this.style.borderStyle='none'\"><span class=\"STYLE3\"><a target=\"I2\" href=\"");
      out.print(son.getUrl());
      out.write('"');
      out.write('>');
      out.print(son.getName() );
      out.write("</a></span></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  ");
 break;
                  		} 
				     }
                  }
      out.write("\r\n");
      out.write("                </table></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"5\"><img src=\"images/main_52.gif\" width=\"151\" height=\"5\" /></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></div></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          \r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("     ");
} 
      out.write("\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"18\" background=\"images/main_58.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"18\" valign=\"bottom\"><div align=\"center\" class=\"STYLE3\">版本：2008V1.0</div></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showsubmenu(sid)\r\n");
      out.write("{\r\n");
      out.write("whichEl = eval(\"submenu\" + sid);\r\n");
      out.write("imgmenu = eval(\"imgmenu\" + sid);\r\n");
      out.write("if (whichEl.style.display == \"none\")\r\n");
      out.write("{\r\n");
      out.write("eval(\"submenu\" + sid + \".style.display=\\\"\\\";\");\r\n");
      out.write("imgmenu.background=\"images/main_47.gif\";\r\n");
      out.write("}\r\n");
      out.write("else\r\n");
      out.write("{\r\n");
      out.write("eval(\"submenu\" + sid + \".style.display=\\\"none\\\";\");\r\n");
      out.write("imgmenu.background=\"images/main_48.gif\";\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
