/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-07-22 03:28:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.CIMS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gxlq.entity.Operator;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxlq.entity.Operator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");

	Object obj = session.getAttribute("OPERATOR");
	Operator operator = (Operator)obj;

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>无标题文档</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write(".STYLE1 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write(".STYLE2 {font-size: 9px}\r\n");
      out.write(".STYLE3 {\r\n");
      out.write("\tcolor: #033d61;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("    function tc(){\r\n");
      out.write("    \t//根据id获取html页面中的表单，并提交\r\n");
      out.write("    \twindow.location.href=\"http://192.168.1.167:8080/cims_gjmy/exit\";\r\n");
      out.write("    }\r\n");
      out.write("    function xg(){\r\n");
      out.write("    \t//根据id获取html页面中的表单，并提交\r\n");
      out.write("    \t//window.location.href=\"http://192.168.1.55:8080/cims/tab/updateoperator.jsp\";\r\n");
      out.write("    \t//window.top 获取浏览器顶层窗口\r\n");
      out.write("    \t//window.top.frames[1]获取浏览器顶层窗口Frame区，通过下标定位某个区，此处为mainFrame\r\n");
      out.write("    \t//window.top.frames[1].I3.I2]获取浏览器顶层窗口Frame区，通过下标定位某个区及其内部“子frame区”，此处为I2\r\n");
      out.write("    \twindow.top.frames[1].I3.I2.location.href=\"http://192.168.1.167:8080/cims_gjmy/CIMS/tab/updateoperator.jsp\";\r\n");
      out.write("    \t//window.alert(\"");
      out.print(operator.getRole().getId());
      out.write("\"); //1\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"70\" background=\"images/main_05.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"24\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"270\" height=\"24\" background=\"images/main_03.gif\">&nbsp;</td>\r\n");
      out.write("            <td width=\"505\" background=\"images/main_04.gif\">&nbsp;</td>\r\n");
      out.write("            <td>&nbsp;</td>\r\n");
      out.write("            <td width=\"21\"><img src=\"images/main_07.gif\" width=\"21\" height=\"24\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"38\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"270\" height=\"38\" background=\"images/main_09.gif\">&nbsp;</td>\r\n");
      out.write("            <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"77%\" height=\"25\" valign=\"bottom\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td width=\"50\" height=\"19\"><div align=\"center\"><img src=\"images/main_12.gif\" width=\"49\" height=\"19\"></div></td>\r\n");
      out.write("                    <td width=\"50\"><div align=\"center\"><img src=\"images/main_14.gif\" width=\"48\" height=\"19\"></div></td>\r\n");
      out.write("                    <td width=\"50\"><div align=\"center\"><img src=\"images/main_16.gif\" width=\"48\" height=\"19\"></div></td>\r\n");
      out.write("                    <td width=\"50\"><div align=\"center\"><img src=\"images/main_18.gif\" width=\"48\" height=\"19\"></div></td>\r\n");
      out.write("                    <td width=\"50\"><div align=\"center\"><img src=\"images/main_20.gif\" width=\"48\" height=\"19\" onclick=\"tc()\"></div></td>\r\n");
      out.write("                    <td width=\"26\"><div align=\"center\"><img src=\"images/main_21.gif\" width=\"26\" height=\"19\"></div></td>\r\n");
      out.write("                    <td width=\"100\"><div align=\"center\"><img src=\"images/main_22.gif\" width=\"98\" height=\"19\" onclick=\"xg()\"></div></td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("                <td width=\"220\" valign=\"bottom\"  nowrap=\"nowrap\"><div align=\"right\"><span class=\"STYLE1\"><span class=\"STYLE2\">■</span> 今天是：20087年5月12日 星期一</span></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"21\"><img src=\"images/main_11.gif\" width=\"21\" height=\"38\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"8\" style=\" line-height:8px;\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"270\" background=\"images/main_29.gif\" style=\" line-height:8px;\">&nbsp;</td>\r\n");
      out.write("            <td width=\"505\" background=\"images/main_30.gif\" style=\" line-height:8px;\">&nbsp;</td>\r\n");
      out.write("            <td style=\" line-height:8px;\">&nbsp;</td>\r\n");
      out.write("            <td width=\"21\" style=\" line-height:8px;\"><img src=\"images/main_31.gif\" width=\"21\" height=\"8\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"28\" background=\"images/main_36.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"177\" height=\"28\" background=\"images/main_32.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"20%\"  height=\"22\">&nbsp;</td>\r\n");
      out.write("            <td width=\"59%\" valign=\"bottom\"><div align=\"center\" class=\"STYLE1\">\r\n");
      out.write("            当前用户：");
      out.print(session.getAttribute("OPERATOR")!=null?((Operator)session.getAttribute("OPERATOR")).getUsername():"未登录" );
      out.write("\r\n");
      out.write("                <!-- EL表达式从会话session中根据key获取value,形如\"导航链\" -->\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("              </div></td>\r\n");
      out.write("            <td width=\"21%\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"65\" height=\"28\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"23\" valign=\"bottom\"><table width=\"58\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr> \r\n");
      out.write("                    <td height=\"20\" style=\"cursor:hand\" onMouseOver=\"this.style.backgroundImage='url(images/bg.gif)';this.style.borderStyle='solid';this.style.borderWidth='1';borderColor='#a6d0e7'; \"onmouseout=\"this.style.backgroundImage='url()';this.style.borderStyle='none'\"> <div align=\"center\" class=\"STYLE3\">业务中心</div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"3\"><img src=\"images/main_34.gif\" width=\"3\" height=\"28\"></td>\r\n");
      out.write("            <td width=\"63\"><table width=\"58\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" style=\"cursor:hand\" onMouseOver=\"this.style.backgroundImage='url(images/bg.gif)';this.style.borderStyle='solid';this.style.borderWidth='1';borderColor='#a6d0e7'; \"onmouseout=\"this.style.backgroundImage='url()';this.style.borderStyle='none'\"><div align=\"center\" class=\"STYLE3\">系统管理</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"3\"><img src=\"images/main_34.gif\" width=\"3\" height=\"28\"></td>\r\n");
      out.write("            <td width=\"63\"><table width=\"58\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" style=\"cursor:hand\" onMouseOver=\"this.style.backgroundImage='url(images/bg.gif)';this.style.borderStyle='solid';this.style.borderWidth='1';borderColor='#a6d0e7'; \"onmouseout=\"this.style.backgroundImage='url()';this.style.borderStyle='none'\"><div align=\"center\" class=\"STYLE3\">通讯录</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"3\"><img src=\"images/main_34.gif\" width=\"3\" height=\"28\"></td>\r\n");
      out.write("            <td width=\"63\"><table width=\"58\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" style=\"cursor:hand\" onMouseOver=\"this.style.backgroundImage='url(images/bg.gif)';this.style.borderStyle='solid';this.style.borderWidth='1';borderColor='#a6d0e7'; \"onmouseout=\"this.style.backgroundImage='url()';this.style.borderStyle='none'\"><div align=\"center\" class=\"STYLE3\">数据管理</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"3\"><img src=\"images/main_34.gif\" width=\"3\" height=\"28\"></td>\r\n");
      out.write("            <td width=\"63\"><table width=\"58\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" style=\"cursor:hand\" onMouseOver=\"this.style.backgroundImage='url(images/bg.gif)';this.style.borderStyle='solid';this.style.borderWidth='1';borderColor='#a6d0e7'; \"onmouseout=\"this.style.backgroundImage='url()';this.style.borderStyle='none'\"><div align=\"center\" class=\"STYLE3\">统计报表</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"3\"><img src=\"images/main_34.gif\" width=\"3\" height=\"28\"></td>\r\n");
      out.write("            <td width=\"63\"><table width=\"58\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" style=\"cursor:hand\" onMouseOver=\"this.style.backgroundImage='url(images/bg.gif)';this.style.borderStyle='solid';this.style.borderWidth='1';borderColor='#a6d0e7'; \"onmouseout=\"this.style.backgroundImage='url()';this.style.borderStyle='none'\"><div align=\"center\" class=\"STYLE3\">业务管理</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"3\"><img src=\"images/main_34.gif\" width=\"3\" height=\"28\"></td>\r\n");
      out.write("            <td width=\"63\"><table width=\"58\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" style=\"cursor:hand\" onMouseOver=\"this.style.backgroundImage='url(images/bg.gif)';this.style.borderStyle='solid';this.style.borderWidth='1';borderColor='#a6d0e7'; \"onmouseout=\"this.style.backgroundImage='url()';this.style.borderStyle='none'\"><div align=\"center\" class=\"STYLE3\">系统配置</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td width=\"3\"><img src=\"images/main_34.gif\" width=\"3\" height=\"28\"></td>\r\n");
      out.write("            <td width=\"63\"><table width=\"58\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" style=\"cursor:hand\" onMouseOver=\"this.style.backgroundImage='url(images/bg.gif)';this.style.borderStyle='solid';this.style.borderWidth='1';borderColor='#a6d0e7'; \"onmouseout=\"this.style.backgroundImage='url()';this.style.borderStyle='none'\"><div align=\"center\" class=\"STYLE3\">升级维护</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            <td>&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"21\"><img src=\"images/main_37.gif\" width=\"21\" height=\"28\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
